# NumPy - Arithmetic Operations
- Arithmetic operations are used for numerical computation, and we can perform them on arrays using NumPy. With NumPy, we can quickly add, subtract, multiply, divide, and raise elements to a power in an array. NumPy performs these operations even with large amounts of data.

  ### Some arithmetic functions
  1. np.add()
  2. np.subtract()
  3. np.multiply()
  4. np.divide()
  5. np.power()
  6. np.mod()
  

In [1]:
import numpy as np

a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
# Addition of Arrays
res = np.add(a, b)
print(res)

# Subtraction of Arrays
res = np.subtract(a, b)
print(res)

# Multiplication of Arrays
res = np.multiply(a, b)
print(res)

# Division of Arrays
res = np.divide(a, b)
print(res)

# Exponentiation (Power)
res = np.power(a, b)
print(res)

# Modulus Operation
res = np.mod(a, b)
print(res)

[  7  77  23 130]
[ 3 67  3 70]
[  10  360  130 3000]
[ 2.5        14.4         1.3         3.33333333]
[                 25          1934917632        137858491849
 1152921504606846976]
[ 1  2  3 10]


## numpy.sum() 
This function returns the sum of array elements over the specified axis.

<i> Syntax: numpy.sum(arr, axis, dtype, out): 
##### Parameters: 

- arr: Input array. 
- axis: The axis along which we want to calculate the sum value. Otherwise, it will consider arr to be flattened(works on all the axes). axis = 0 means along the column and axis = 1 means working along the row. 
- out: Different array in which we want to place the result. The array must have the same dimensions as the expected output. The default is None. 
- initial : [scalar, optional] Starting value of the sum. 
- Return: Sum of the array elements (a scalar value if axis is none) or array with sum values along the specified axis.

### Example 1: 
- This Python program uses numpy.sum() to calculate the sum of a 1D array. It demonstrates summing with different data types (uint8 and float32) and checks if the result's data type matches np.uint and np.float. The output shows how the sum can vary with different types.

In [6]:
# numpy.sum() method
import numpy as np 
	
# 1D array 
arr = [20, 2, .2, 10, 4] 

print("\nSum of arr : ", np.sum(arr)) 

print("Sum of arr(uint8) : ", np.sum(arr, dtype = np.uint8)) 
print("Sum of arr(float32) : ", np.sum(arr, dtype = np.float32))

print ("\nIs np.sum(arr).dtype == np.uint : ", 
	np.sum(arr).dtype == np.uint) 

print ("Is np.sum(arr).dtype == np.float32 : ", 
	np.sum(arr).dtype == np.float32)


Sum of arr :  36.2
Sum of arr(uint8) :  36
Sum of arr(float32) :  36.2

Is np.sum(arr).dtype == np.uint :  False
Is np.sum(arr).dtype == np.float32 :  False


In [3]:
print(np.__version__)

2.3.5
