# Create NumPy Array

In [4]:
import numpy as np
arr = np.array([1,2,3,5,6])
print(arr)
print(type(arr))

[1 2 3 5 6]
<class 'numpy.ndarray'>


In [16]:
# 0-D Arrays:
arr = np.array(42)
print(arr)
print(type(arr))

# 1-D Arrays:
arr1 = np.array([1,3,6,7,33,2])
print(arr1)

# 2-D Arrays:
arr2 = np.array([[1,3,5],[2,4,6]])
print(arr2)

# 3-D Arrays:
arr3=np.array([[[1,2,3],[1,5,7]],[[2,4,8],[7,9,3]],[[2,4,6],[7,3,6]]])
print(arr3)

42
<class 'numpy.ndarray'>
[ 1  3  6  7 33  2]
[[1 3 5]
 [2 4 6]]
[[[1 2 3]
  [1 5 7]]

 [[2 4 8]
  [7 9 3]]

 [[2 4 6]
  [7 3 6]]]
0


In [17]:
# Check Arrays dimensions
print(arr.ndim)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

0
1
2
3


In [21]:
arr_n = np.array([1,3,5,7,9], ndmin=5)
print(arr_n)
print('Numner of Dimensions : ', arr_n.ndim)

[[[[[1 3 5 7 9]]]]]
Numner of Dimensions :  5
